---
title: "接口问题列表"
---



### 电竞大厅

* CP管理：编辑时是否有效的状态不生效；新增后要割一段时间才能刷新出来【已修复】
* 公告管理：编辑后数据更新不同步；新增提示保存成功，但查询接口没有新增的数据；【已修复】
* 推荐管理：query查询接口里有某id的数据,但是view接口里却没有数据：【已修复】
  * ![mark](http://7xlnr9.com1.z0.glb.clouddn.com/blog/20170804/225004034.png)

  * ![mark](http://7xlnr9.com1.z0.glb.clouddn.com/blog/20170804/225023700.png)

  * 新增接口参数有问题，与现网不一致，导致不匹配【重庆现网看，不需要apid，但是新增时提示apid不能为空】：

    ```
    "{\"message\":\"Traceback (most recent call last):\\n  File \\\"\\\/home\\\/wangjushidaigame\\\/rh\\\/video_dx_sichuan\\\/base_api\\\/views.py\\\", line 330, in save\\n    ret = instance.save()\\n  File \\\"\\\/usr\\\/local\\\/python\\\/lib\\\/python2.7\\\/site-packages\\\/Django-1.7.9-py2.7.egg\\\/django\\\/db\\\/models\\\/base.py\\\", line 589, in save\\n    force_update=force_update, update_fields=update_fields)\\n  File \\\"\\\/usr\\\/local\\\/python\\\/lib\\\/python2.7\\\/site-packages\\\/Django-1.7.9-py2.7.egg\\\/django\\\/db\\\/models\\\/base.py\\\", line 617, in save_base\\n    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)\\n  File \\\"\\\/usr\\\/local\\\/python\\\/lib\\\/python2.7\\\/site-packages\\\/Django-1.7.9-py2.7.egg\\\/django\\\/db\\\/models\\\/base.py\\\", line 698, in _save_table\\n    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)\\n  File \\\"\\\/usr\\\/local\\\/python\\\/lib\\\/python2.7\\\/site-packages\\\/Django-1.7.9-py2.7.egg\\\/django\\\/db\\\/models\\\/base.py\\\", line 731, in _do_insert\\n    using=using, raw=raw)\\n  File \\\"\\\/usr\\\/local\\\/python\\\/lib\\\/python2.7\\\/site-packages\\\/Django-1.7.9-py2.7.egg\\\/django\\\/db\\\/models\\\/manager.py\\\", line 92, in manager_method\\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\\n  File \\\"\\\/usr\\\/local\\\/python\\\/lib\\\/python2.7\\\/site-packages\\\/Django-1.7.9-py2.7.egg\\\/django\\\/db\\\/models\\\/query.py\\\", line 921, in _insert\\n    return query.get_compiler(using=using).execute_sql(return_id)\\n  File \\\"\\\/usr\\\/local\\\/python\\\/lib\\\/python2.7\\\/site-packages\\\/Django-1.7.9-py2.7.egg\\\/django\\\/db\\\/models\\\/sql\\\/compiler.py\\\", line 921, in execute_sql\\n    cursor.execute(sql, params)\\n  File \\\"\\\/usr\\\/local\\\/python\\\/lib\\\/python2.7\\\/site-packages\\\/Django-1.7.9-py2.7.egg\\\/django\\\/db\\\/backends\\\/utils.py\\\", line 65, in execute\\n    return self.cursor.execute(sql, params)\\n  File \\\"\\\/usr\\\/local\\\/python\\\/lib\\\/python2.7\\\/site-packages\\\/Django-1.7.9-py2.7.egg\\\/django\\\/db\\\/backends\\\/mysql\\\/base.py\\\", line 134, in execute\\n    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])\\n  File \\\"\\\/usr\\\/local\\\/python\\\/lib\\\/python2.7\\\/site-packages\\\/Django-1.7.9-py2.7.egg\\\/django\\\/db\\\/backends\\\/mysql\\\/base.py\\\", line 129, in execute\\n    return self.cursor.execute(query, args)\\n  File \\\"build\\\/bdist.linux-x86_64\\\/egg\\\/MySQLdb\\\/cursors.py\\\", line 174, in execute\\n    self.errorhandler(self, exc, value)\\n  File \\\"build\\\/bdist.linux-x86_64\\\/egg\\\/MySQLdb\\\/connections.py\\\", line 36, in defaulterrorhandler\\n    raise errorclass, errorvalue\\nIntegrityError: (1048, \\\"Column 'apid' cannot be null\\\")\\n\",\"code\":-1,\"id\":null}"
    ```

    ​​

